#pragma once
#define NB_MAX_STR	1000//Nombre max de string gérées dans la classe


//Definitions Messages
#define MESSAGE_ACTIVATION_ROBOT	0
#define MESSAGE_DESACTIVATION_ROBOT	1
#define MESSAGE_ACTIVATION_PESON	2
#define MESSAGE_DESACTIVATION_PESON	3
#define MESSAGE_ACTIVATION_DMX	4
#define MESSAGE_DESACTIVATION_DMX	5
#define MESSAGE_INHIBITION_INTERDITE	6
#define MESSAGE_OFEXIST_ASKREPRISE	7
#define MESSAGE_CHARGEMENTOF_OK	8
#define MESSAGE_CHARGEMENTOF_BLOQUE	9
#define MESSAGE_ASK_SAUVEGARDE	10
#define MESSAGE_HORSLIMITES	11
#define MESSAGE_JOURNAL_CSVOLD	12
#define MESSAGE_JOURNAL_RECETTEMANU	13
#define MESSAGE_CAMERA_ATTENTEREPONSE	14
#define MESSAGE_CAMERA_REPONSEOK	15
#define MESSAGE_DMXCONF_ENCOURS	16
#define MESSAGE_DMXCONF_OK	17
#define MESSAGE_DMXCONF_NOK	18
#define MESSAGE_DMXCONF_NEXT 61
#define MESSAGE_INIT_OK	19
#define MESSAGE_INITNOK_DMX	20
#define MESSAGE_INITNOK_ROBOT	21
#define MESSAGE_CSVFILES_EC	22
#define MESSAGE_CSVFILES_OK	23
#define MESSAGE_CSVFILES_NOK	24
#define MESSAGE_SELECOF_EC	25
#define MESSAGE_SELECOF_OK	26
#define MESSAGE_SELECOF_NOK	27
#define MESSAGE_USER_INFOS_PASSWORD	28
#define MESSAGE_USER_INFOS_PASSWORDNOK	29
#define MESSAGE_USER_INFOS_DESACTIVATE_F	30
#define MESSAGE_USER_INFOS_DESACTIVATE	31
#define MESSAGE_USER_INFOS_INCONNU	32
#define MESSAGE_USER_INFOS_LOGIN	33
#define MESSAGE_USER_INFOS_NOTMANAGER	34
#define MESSAGE_PRELEV_TITRE	35
#define MESSAGE_PRELEV_TRACA_F	36
#define MESSAGE_PRELEV_SAISIENOK	37
#define MESSAGE_MODIF_PARAM_F	38
#define MESSAGE_VALID_PESON_NOK	39

#define MESSAGE_DEFAUT_AiETUYEUSE 40
#define MESSAGE_DEFAUT_AiROBOTS 41
#define MESSAGE_DEFAUT_AFCyETUYEUSE 42
#define MESSAGE_DEFAUT_AFCyROBOTS 43
#define MESSAGE_DEFAUT_MIXUP 49

#define MESSAGE_VIDAGE_NOK 44
#define MESSAGE_RECETTE_NOK 45
#define MESSAGE_MAINTENANCE_NOK 46
#define MESSAGE_RECETTEVISION_NOK 47
#define MESSAGE_ETALONS_NOK 48

#define MESSAGE_RECETTE_DEJACHARGEE 50
#define MESSAGE_ATTENTE_CYCLEENCOURS 51
#define MESSAGE_ASK_ARRETCYCLE 52
#define MESSAGE_ASK_MACHINENONVIDE 53
#define MESSAGE_JOURNAL_MACHINENONVIDE 54
#define MESSAGE_TIMEOUT 55
#define MESSAGE_CAMERA_TIMEOUT 56
#define MESSAGE_VIDAGE_NOKMAINTENANCE 57
#define MESSAGE_PRODUCTIONARRET_NOK 58
#define MESSAGE_HORSPRODUCTION_NOK 59
#define MESSAGE_HORSOUARRETPRODUCTION_NOK 60
#define MESSAGE_ASK_AJOUTCOM_MIXUP 62
#define MESSAGE_ETALONNAGE_ETUI_NOK 63
#define MESSAGE_MACHINEVIDE_NOK 64



class CMyStrTable
{
public:
	CMyStrTable(void);
	~CMyStrTable(void);

	int NbStr;
	int Index[NB_MAX_STR];

	CStringArray m_Codes;
	CStringArray m_String;

	CString strErreur;

	int ChargerFromBase(void);
	CString GetStr(int CleMessage);
	CString GetStr(CString strCode);
	CString GetCode(int CleMessage);
};
