//{{NO_DEPENDENCIES}}
// fichier Include Microsoft Visual C++.
// Utilisé par BaseFenetre.rc
//
#define ID_BUTOFENCOURS                 3
#define IDC_ZOOMPLUS                    3
#define IDCANCEL3                       4
#define ID_BUTTOUS                      4
#define IDC_ZOOMMOINS                   4
#define ID_BUTSELECTION                 5
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_FORMMENUMACHINE             101
#define IDD_DIALOGPARAM                 103
#define IDD_DIAGLISTEREQ                104
#define IDD_FORMCAMSIM                  106
#define IDD_FORMSTATUS                  122
#define IDD_LISTEAPP                    123
#define IDC_LIST1                       125
#define IDC_LIST3                       126
#define IDR_MAINFRAME                   128
#define IDR_BaseFenetreTYPE             129
#define IDR_OUTILSVUES                  130
#define IDD_SESSION                     131
#define IDD_DIALCAMERAS                 132
#define IDD_DIALALARMES                 133
#define IDD_DIALVISION                  134
#define IDB_BITMAP1                     135
#define IDD_DIALROBOT                   136
#define IDD_DIALLOG_SAISIE              139
#define IDD_DIALMACHINE                 141
#define IDD_DIAG_CAMERA                 142
#define IDR_MENU_CAMERA                 143
#define IDD_DIALOG1                     143
#define IDD_DIAL_PESONS                 143
#define IDD_DIAL_OPC                    145
#define IDB_ALARME_B                    146
#define IDB_ALARME_R                    147
#define IDD_DIALCHARGEMENT              148
#define IDD_DIALINITIALISATION          149
#define IDD_DIALVALIDATIONOF            150
#define IDD_DIAL_VALIDATIONLOT          151
#define IDD_DIALMIXUP                   152
#define IDB_BMP_DALSA                   153
#define IDD_DIALDMX                     154
#define IDB_BIT_ACYRUS                  156
#define IDD_DIAL_AFFRECETTE             157
#define IDD_DIALSELECTPRINT             158
#define IDD_DIALOG2                     159
#define IDD_DIAL_PESEE                  160
#define IDD_DIALSELECTROI               161
#define IDD_DIALSELECTPLANCOLOR         162
#define IDB_FLECHEBAS                   163
#define IDD_DIALETIQUETTE               163
#define IDD_DIAL_MODIFPIECE             164
#define IDB_FLECHEDROITE                165
#define IDD_DIAL_DEFAUTPISTE            165
#define IDB_FLECHEGAUCHE                166
#define IDB_FLECHEHAUT                  167
#define IDB_ZOOMMOINS                   168
#define IDB_ZOOMPLUS                    169
#define IDB_ANNULER                     170
#define IDB_VALIDER                     171
#define IDB_BMP_DALSA1                  172
#define IDB_BIT_ACYRUS1                 173
#define IDB_STRETCH                     178
#define IDB_STRETCHHRZ                  181
#define IDB_STRETCHVRT                  182
#define IDB_BMP_DALSA2                  183
#define IDB_BITMAP2                     184
#define IDB_BIT_ACYRUS2                 185
#define IDB_ALARME_R1                   186
#define IDB_ALARME_B1                   187
#define IDD_DIAG_SPLASH                 193
#define IDC_GRILLE                      1000
#define IDC_EDIT1                       1000
#define IDC_BUTTON12                    1000
#define IDC_SLIDER                      1001
#define IDC_BUTTON2                     1001
#define IDC_GRILLE2                     1001
#define IDC_BUTTON6                     1002
#define IDC_BUTALARME                   1003
#define IDC_BUTTON7                     1003
#define IDC_EDIT2                       1003
#define IDC_BUT_MOINS                   1004
#define IDC_BUTSNAP                     1004
#define IDC_BUTTON8                     1004
#define IDC_EDITLABELSELEC              1005
#define IDC_BUTTON1                     1005
#define IDC_BUTTON_TEST                 1005
#define IDC_BUTTON9                     1005
#define IDC_BUT_ROBOTOFF                1005
#define IDC_BUT_ONE_MESURE              1005
#define IDC_EDITLABELVALMAX             1006
#define IDC_BUTTON_TEST2                1006
#define IDC_BUTTON10                    1006
#define IDC_BUT_ROBOT_PARKING           1006
#define IDC_BUT_MESURES                 1006
#define IDC_EDITLABELVALMIN             1007
#define IDC_BUTTON11                    1007
#define IDC_BUT_ROBOT_VIDAGE            1007
#define IDC_BUT_TARE                    1007
#define IDC_BUT_WRITECMD                1007
#define IDC_BUTFREERUN                  1007
#define IDC_BUTTON5                     1007
#define IDC_BUT_OFF                     1008
#define IDC_EDIT_CMD                    1008
#define IDC_BUTFREERUN2                 1008
#define IDC_BUTIMAGES                   1008
#define IDC_EDITVALSLIDER               1009
#define IDC_GRILLEETATS                 1009
#define IDC_CB_NUMROBOT                 1010
#define IDD_FORMDALSASPYDER             1010
#define IDC_RADIO_PESON1                1011
#define IDC_BUTTON4                     1012
#define IDC_RADIO_PESON2                1012
#define IDC_RADIO_PESON3                1013
#define IDC_RADIO_PESON4                1014
#define IDC_RADIO_ROBOT1                1014
#define IDC_T_ITERATION                 1015
#define IDC_RADIO_PESON5                1015
#define IDC_RADIO_ROBOT2                1015
#define IDC_RADIO_PESON6                1016
#define IDC_RADIO_ROBOT3                1016
#define IDC_LISTDEFAUTS                 1016
#define IDD_WNDMESSCOM                  1016
#define IDC_RADIO_PESONALL              1017
#define IDC_RADIO_ROBOTALL              1017
#define IDD_DIALCAMERAS1                1017
#define IDC_RADROBOTS                   1018
#define IDC_BUTSETVALUE                 1018
#define IDD_FORMBASE                    1018
#define IDC_RADRECETTE                  1019
#define IDD_DIALOGPARAM1                1019
#define IDC_SB_TEMPSEXPO                1020
#define IDC_RAD_RAF_AUTO                1020
#define IDC_RADPROCESSW                 1020
#define IDC_T_TEMPSEXPO                 1021
#define IDC_RAD_RAF_MANU                1021
#define IDC_RADROBOTREAD1               1021
#define IDC_BUT_PLUS                    1022
#define IDC_SB_GAIN                     1022
#define IDC_BUTGETVAL                   1022
#define IDC_T_GAIN                      1023
#define IDC_BUTSETVAL                   1023
#define IDC_VOYANT_ROBOT1               1023
#define IDC_EDIT4                       1023
#define IDC_BUT_PLUS2                   1023
#define IDC_BUT_EDIT                    1023
#define IDC_SB_MODE                     1024
#define IDC_VOYANT_ROBOT2               1024
#define IDC_EDIT10                      1024
#define IDC_BUTSETVAL2                  1024
#define IDC_BUTRESETOPCCOM              1024
#define IDC_T_MODE                      1025
#define IDC_VOYANT_ROBOT3               1025
#define IDC_RADROBOTWRITE1              1025
#define IDC_T_FICHIER                   1026
#define IDC_VOYANT_ROBOT4               1026
#define IDC_VOYANT_COM                  1026
#define IDC_RADROBOTREAD2               1026
#define IDC_T_NUMPORT                   1027
#define IDC_VOYANT_PESON1               1027
#define IDC_RADROBOTWRITE2              1027
#define IDC_T_NUMSERIAL                 1028
#define IDC_STATIC_MENUMACHINE          1028
#define IDC_VOYANT_PESON2               1028
#define IDC_RADROBOTREAD3               1028
#define IDC_EVENTSLIST                  1029
#define IDC_VOYANT_PESON3               1029
#define IDC_RADROBOTWRITE3              1029
#define IDC_VOYANT_PESON4               1030
#define IDC_TEXT_ETATMACHINE            1030
#define IDC_RADPROCESSW2                1030
#define IDC_DEFAUTENCOURS               1030
#define IDC_VOYANT_PESON5               1031
#define IDC_STATICMENU_STATUS           1031
#define IDC_TEXT_UTILISATEUR            1031
#define IDC_BUT_OPENDOC                 1031
#define IDC_RADPROCESSW3                1031
#define IDC_VOYANT_PESON6               1032
#define IDC_RADROBOTREAD4               1032
#define IDC_VOYANT_DMX1                 1033
#define IDC_STATICTEXTMIXUP             1033
#define IDC_RADROBOTREAD5               1033
#define IDC_RADROBOTWRITE4              1033
#define IDC_VOYANT_DMX2                 1034
#define IDC_EDIT_NUMLOT                 1034
#define IDC_RADROBOTREAD6               1034
#define IDC_RADROBOTWRITE5              1034
#define IDC_VOYANT_DMX3                 1035
#define IDC_BUT_SAVEMESURESDYNA         1035
#define IDC_EDIT_NUMOF                  1035
#define IDC_RADROBOTREAD7               1035
#define IDC_RADROBOTWRITE6              1035
#define IDC_VOYANT_ROBOTM10             1036
#define IDC_MENU_PESON                  1036
#define IDC_EDIT_IDETUI                 1036
#define IDC_VOYANT_CAM1                 1036
#define IDC_RADROBOTREAD8               1036
#define IDC_RADROBOTWRITE7              1036
#define IDC_MENUROBOT                   1037
#define IDC_EDIT_IDNOTICE1              1037
#define IDC_TEXT_DESCRIPTION            1037
#define IDC_RADROBOTREAD9               1037
#define IDC_STATICMENU_DIALMACHINE      1038
#define IDC_EDIT_IDNOTICE2              1038
#define IDC_RADROBOTREAD10              1038
#define IDC_RAD_TYPE_SACHET             1039
#define IDC_TEXT_OF                     1039
#define IDC_RAD_TYPE_BLISTER            1040
#define IDC_TEXT_ARTICLE                1040
#define IDC_TEXT_PISTE1                 1040
#define IDC_RAD_NOETIQETUI              1041
#define IDC_TEXT_LOT                    1041
#define IDC_TEXT_OF3                    1041
#define IDC_TEXT_PISTE2                 1041
#define IDC_RAD_SMALLETIQETUI           1042
#define IDC_VOYANT_CAM2                 1042
#define IDC_RAD_TALLETIQETUI            1043
#define IDC_VOYANT_CAM3                 1043
#define IDC_VOYANT_CAMBOITE             1043
#define IDC_RAD_NOETIQNOTICE1           1044
#define IDC_VOYANT_CAM4                 1044
#define IDC_VOYANT_IMPCELLEMENT         1044
#define IDC_RAD_SMALLETIQNOTICE1        1045
#define IDC_RAD_AUTORAF                 1045
#define IDC_VOYANT_CAM5                 1045
#define IDC_VOYANT_PESAGE               1045
#define IDC_BUT_PAVNUM_8                1046
#define IDC_RAD_TALLETIQNOTICE1         1046
#define IDC_RAD_MANURAF                 1046
#define IDC_TEXT_CADENCE                1046
#define IDC_CAM_LAIZE                   1047
#define IDC_BUT_PAVNUM_9                1047
#define IDC_RAD_NOETIQNOTICE2           1047
#define IDC_VOYANT_WOLKE                1047
#define IDC_VOYANT_LECTCELLEMENT        1047
#define IDC_BUT_PAVNUM_7                1048
#define IDC_RAD_SMALLETIQNOTICE2        1048
#define IDC_VOYANT_WOLKE2               1048
#define IDC_VOYANT_ETIQUETTE            1048
#define IDC_VOYANT_IMPWOLKE             1048
#define IDC_SB_ETIQUETTE                1049
#define IDC_BUT_PAVNUM_5                1049
#define IDC_RAD_TALLETIQNOTICE2         1049
#define IDC_VOYANT_LECTWOLK             1049
#define IDC_VOYANT_LECTWOLKE            1049
#define IDC_T_ETIQUETTE                 1050
#define IDC_BUT_PAVNUM_6                1050
#define IDC_STATICMENU_CHARGEMENT       1050
#define IDC_SB_EXT_SIZE                 1051
#define IDC_BUT_PAVNUM_4                1051
#define IDC_STATIC_NUMLOT               1051
#define IDC_T_MOYENNE                   1052
#define IDC_BUT_PAVNUM_2                1052
#define IDC_STATICMENU_VALIDLOT         1052
#define IDC_SB_EXT_POS                  1053
#define IDC_BUT_PAVNUM_3                1053
#define IDC_RADDMX1                     1053
#define IDC_STATICMENU_VALIDLOT2        1053
#define IDC_SB_NOK                      1054
#define IDC_BUT_PAVNUM_1                1054
#define IDC_RADDMX2                     1054
#define IDC_CAM_LG                      1055
#define IDC_BUT_PAVNUM_PT               1055
#define IDC_RADDMX3                     1055
#define IDC_CAM_LD                      1056
#define IDC_BUT_PAVNUM_0                1056
#define IDC_STATICMENU_DMX              1056
#define IDC_T_NOK                       1057
#define IDC_BUT_PAVNUM_RET              1057
#define IDC_IMAGE                       1057
#define IDC_T_EXT_POS                   1058
#define IDC_BUT_SYNCON                  1058
#define IDC_T_EXT_SIZE                  1059
#define IDC_BUT_SYNCOFF                 1059
#define IDC_CAM_OPEN                    1060
#define IDC_BUT_COMPTEUR                1060
#define IDC_CAM_CLOSE                   1061
#define IDC_BUT_COMPTEUR2               1061
#define IDC_CAM_LIRE                    1062
#define IDC_CAM_CONFIG                  1063
#define IDC_RAD_POS                     1063
#define IDC_RAD_POS2                    1064
#define IDC_RAD_POS3                    1065
#define IDC_CAM_SNAP                    1066
#define IDC_RAD_POS4                    1066
#define IDC_SB_NBPLI                    1067
#define IDC_GRILLEVISION                1067
#define IDC_T_NBPLIEJECTE               1068
#define IDC_RAD_GENERAL                 1068
#define IDC_RAD_POS5                    1068
#define IDC_RAD_VISION                  1069
#define IDC_GRILLEVISION2               1069
#define IDC_LIST2                       1071
#define IDC_BUTEDITPARAM                1071
#define IDC_LIST_MESURESDYNA            1072
#define IDC_BUTSAVEPARAM                1072
#define IDC_GRILLERECETTE               1072
#define IDC_LIST_VISION                 1073
#define IDC_STATICMENUVISION            1074
#define IDC_VOYANT_AUTO                 1075
#define IDC_LIST_VISIONTEMPS            1075
#define IDC_CAM_SHIFT                   1076
#define IDC_STATICINFOS                 1076
#define IDC_VOYANT_VIDAGE               1076
#define IDC_STATICMENU_MIXUP            1076
#define IDC_BUTEDITPARAM2               1076
#define IDC_VOYANT_VIDAGE2              1077
#define IDC_VOYANT_MAINTENANCE          1077
#define IDC_STATICMENU_ALARMES          1077
#define IDC_STATICMENU_ALARMES2         1078
#define IDC_STATIC_DESCRIPTION          1079
#define IDC_STATIC_OF                   1080
#define IDC_STATIC_ARTICLE              1081
#define IDC_STATIC_LOT                  1082
#define IDC_STATIC_RECETTEENCOURS       1083
#define IDC_STATIC_LOT2                 1083
#define IDC_STATIC_CADENCE              1083
#define IDC_STATIC_COMPTAGE             1084
#define IDC_STATIC_CAD_VUS              1084
#define IDC_STATICMENU_DIALINIT         1085
#define IDC_STATIC_CAD_PRIS             1085
#define IDC_STATICMENU_VALIDOF          1086
#define IDC_STATIC_CAD_PISTE1           1086
#define IDC_LIST_DEFMACHINE             1087
#define IDC_BUT_PAVNUM_MOINS2           1088
#define IDC_STATIC_TITRE                1088
#define IDC_STATIC_CAD_PISTE2           1088
#define IDC_RADIO_CAM1                  1089
#define IDC_STATIC_CAD_PISTE3           1089
#define IDC_RADIO_CAM2                  1090
#define IDC_RADIO_EXP1                  1090
#define IDC_RADIO_EXP2                  1091
#define IDC_RADIO_EXP3                  1092
#define IDC_STATIC_BALANCE              1092
#define IDC_RADIO_EXP4                  1093
#define IDC_RADIO1                      1093
#define IDC_STATIC_CAD_P1_VUS           1093
#define IDC_EMPLACEMENT_IMG             1094
#define IDC_STATIC_MENU_ETIQUETTE       1094
#define IDC_STATIC_CAD_P2_VUS           1094
#define IDC_STATICMENU_DIALCAMERA       1095
#define IDC_PICTURE                     1095
#define IDC_STATIC_CAD_P3_VUS           1095
#define IDC_RADIO2                      1096
#define IDC_STATICMENU_MODIF            1096
#define IDC_LISTETIQRESULT              1096
#define IDC_STATIC_CAD_P1_PRIS          1096
#define IDC_STATICMENU_MODIFIMG         1097
#define IDC_RAD_FORCAGE1                1097
#define IDC_STATICMENUDEFAUT            1097
#define IDC_STATIC_CAD_P2_PRIS          1097
#define IDC_STATICMENU_MOVE             1098
#define IDC_STATICMENU_MODIFIMG2        1098
#define IDC_RAD_FORCAGE2                1098
#define IDC_STATIC_IMGDEF               1098
#define IDC_STATIC_CAD_P3_PRIS          1098
#define IDC_STATICMENU_MOVE2            1099
#define IDC_FORMULAIRE_EXTRACTION       1099
#define IDC_RAD_FORCAGE3                1099
#define IDC_SCROLLBAR1                  1099
#define IDC_STATIC_CAD_RATIO            1099
#define IDC_PROGRESSAVANCEMENT          1100
#define IDC_RAD_FORCAGE4                1100
#define IDC_SCROLLBAR2                  1100
#define IDC_STATIC_CAD_P1_RATIO         1100
#define IDC_DESCRIPTION                 1101
#define IDC_TEXT_PISTE0                 1101
#define IDC_STATIC_CAD_P2_RATIO         1101
#define IDC_MFCFONTCOMBO1               1102
#define IDC_STATIC_CAD_P3_RATIO         1102
#define IDC_STATIC_CAD_P1_RATIO2        1102
#define IDC_STATIC_CAD_P2_PRIS2         1103
#define IDC_BUTGETVALUE                 1104
#define IDC_STATIC_CAD_P2_RATIO2        1104
#define IDC_STATIC_CAD_P3_PRIS2         1105
#define IDC_CUSTOM1                     1106
#define IDC_STATIC_CAD_P3_RATIO2        1106
#define IDC_CUSTOM2                     1107
#define IDC_STATIC_CAD_P1_VUS2          1107
#define IDC_STATIC_CAD_P1_PRIS2         1108
#define IDC_STATIC_CAD_P2_VUS2          1109
#define IDC_STATIC_CAD_P3_VUS2          1110
#define IDC_STATIC_CAD_P1_VUS3          1111
#define IDC_STATIC_CAD_P1_PRIS3         1112
#define IDC_BUTRESET                    1113
#define IDC_STATIC_CAD_P1_RATIO3        1113
#define IDC_INFOS_ROI                   1114
#define IDC_STATIC_CAD_P2_VUS3          1114
#define IDC_BUTGAUCHE                   1115
#define IDC_STATIC_CAD_P2_PRIS3         1115
#define IDC_BUTDROITE                   1116
#define IDC_STATICRED                   1116
#define IDC_STATIC_CAD_P2_RATIO3        1116
#define IDC_BUTHAUT                     1117
#define IDC_STATICGREEN                 1117
#define IDC_STATIC_CAD_P3_VUS3          1117
#define IDC_BUTBAS                      1118
#define IDC_STATICBLUE                  1118
#define IDC_STATIC_CAD_P3_PRIS3         1118
#define IDC_BUTZOOMPLUS                 1119
#define IDC_RADIOR                      1119
#define IDC_STATIC_CAD_P3_RATIO3        1119
#define IDC_BUTZOOMMOINS                1120
#define IDC_RADIOG                      1120
#define IDC_BUTSTRETCH                  1121
#define IDC_RADIOB                      1121
#define IDC_BUTSTRETCHHRZ               1122
#define IDC_BUTSTRETCHVRT               1123
#define IDC_STATICMENU_PARAMS           1136
#define IDC_SCROLLHORZ                  1148
#define IDC_SCROLLVERT                  1149
#define IDC_SCROLLBARHRZ                1150
#define IDC_SCROLLBARVRT                1151
#define IDC_EDIT_DIAGSAISIE             1159
#define IDD_DIALUTILISATEUR             1160
#define IDC_STATIC_FUTILISATEUR         1161
#define ID_VIEWCAM                      32771
#define ID_VIEWPARAM                    32773
#define ID_VIEWTRAITEMENT               32774
#define ID_VIEWALARMES                  32775
#define ID_VIEWNEW                      32776
#define ID_VIEWROBOT1                   32776
#define ID_VIEWROBOT2                   32777
#define ID_AFFICHAGE_IMAGE0             32779
#define ID_VEWMACHINE                   32779
#define ID_CAMERA_FERMER                32780
#define ID_VIEWMACHINE                  32780
#define ID_AFFICHAGE_IMAGE1             32781
#define ID_LOGIN                        32781
#define ID_AFFICHAGE_IMAGE2             32782
#define ID_VIEWPESONS                   32782
#define ID_BUTVIEWOPC                   32783
#define ID_VIEWOPC                      32784
#define ID_TEST                         32785
#define ID_CAMERA_EXECUTE_ACQUISITION   32794
#define ID_CAMERA_EXECUTE_START         32795
#define ID_CAMERA_EXECUTE_STOP          32796
#define ID_CAMERA_EXECUTE_RECONNAISSANCE 32800
#define ID_CAMERA_FICHIERSOURCE         32804
#define ID_ZONE_1                       32853
#define ID_ZONE_2                       32854
#define ID_ZONE_3                       32855
#define ID_ZONE_P2                      32856
#define ID_ZONE_P3                      32857
#define ID_ZONE_P4                      32858
#define ID_ZONE_4                       32866
#define ID_ZONE_5                       32867
#define ID_ZONE_8                       32868
#define ID_ZONE_9                       32869
#define ID_ZONE_NULL                    32870

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        172
#define _APS_NEXT_COMMAND_VALUE         32787
#define _APS_NEXT_CONTROL_VALUE         1111
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
